import Link from 'next/link';
import Image from 'next/image';
import { Button } from '@/components/ui/button';
import { Card, CardContent } from '@/components/ui/card';
import { Compass, MapPin, Users, Zap, Globe } from 'lucide-react';

const featuredDestinations = [
  { id: 'paris', name: 'Paris, France', img: 'https://picsum.photos/seed/paris/600/400', hint: 'Paris Eiffel' },
  { id: 'tokyo', name: 'Tokyo, Japan', img: 'https://picsum.photos/seed/tokyo/600/400', hint: 'Tokyo skyline' },
  { id: 'bali', name: 'Bali, Indonesia', img: 'https://picsum.photos/seed/bali/600/400', hint: 'Bali beach' },
  { id: 'amalapuram', name: 'Amalapuram, India', img: 'https://picsum.photos/seed/amalapuram/600/400', hint: 'Amalapuram backwaters' },
];

export default function Home() {
  return (
    <div className="flex flex-col gap-16 pb-20">
      {/* Hero Section */}
      <section className="relative h-[80vh] flex items-center justify-center overflow-hidden">
        <div className="absolute inset-0 z-0">
          <Image
            src="https://picsum.photos/seed/travel-hero/1920/1080"
            alt="World Travel"
            fill
            className="object-cover opacity-30"
            priority
            data-ai-hint="World map"
          />
          <div className="absolute inset-0 bg-gradient-to-b from-transparent to-background/90" />
        </div>

        <div className="container mx-auto px-4 relative z-10 text-center space-y-6">
          <h1 className="font-headline text-5xl md:text-7xl font-bold text-primary tracking-tighter max-w-4xl mx-auto leading-tight">
            Discover the World with <span className="text-accent">Local Wisdom</span>
          </h1>
          <p className="text-lg md:text-xl text-muted-foreground max-w-2xl mx-auto font-medium">
            Find expert local guides, explore hidden gems worldwide, and get AI-powered itineraries tailored just for you.
          </p>
          <div className="flex flex-col sm:flex-row gap-4 justify-center pt-4">
            <Link href="/destinations">
              <Button size="lg" className="bg-primary text-white h-14 px-8 text-lg rounded-full">
                Explore Destinations
              </Button>
            </Link>
            <Link href="/guides">
              <Button size="lg" variant="outline" className="h-14 px-8 text-lg rounded-full border-primary text-primary hover:bg-primary/5">
                Find a Local Guide
              </Button>
            </Link>
          </div>
        </div>
      </section>

      {/* Features Section */}
      <section className="container mx-auto px-4">
        <div className="grid md:grid-cols-3 gap-8">
          {[
            {
              icon: Globe,
              title: 'Global Directory',
              desc: 'Every tourist spot across the globe curated and presented for your exploration.'
            },
            {
              icon: Users,
              title: 'Expert Local Guides',
              desc: 'Connect with registered local experts who know the culture and secret spots.'
            },
            {
              icon: Zap,
              title: 'AI Itineraries',
              desc: 'Instant, personalized travel plans generated by our advanced AI travel agent.'
            }
          ].map((feature, i) => (
            <div key={i} className="bg-white p-8 rounded-2xl shadow-sm border border-secondary hover:shadow-md transition-shadow">
              <feature.icon className="w-10 h-10 text-accent mb-4" />
              <h3 className="font-headline text-xl font-semibold mb-2">{feature.title}</h3>
              <p className="text-muted-foreground">{feature.desc}</p>
            </div>
          ))}
        </div>
      </section>

      {/* Featured Destinations */}
      <section className="container mx-auto px-4">
        <div className="flex items-end justify-between mb-8">
          <div>
            <h2 className="font-headline text-3xl font-bold text-primary">Featured Destinations</h2>
            <p className="text-muted-foreground">Start your journey here</p>
          </div>
          <Link href="/destinations" className="text-accent font-semibold hover:underline flex items-center gap-1">
            View All <Compass className="w-4 h-4" />
          </Link>
        </div>
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6">
          {featuredDestinations.map((dest) => (
            <Link key={dest.id} href={`/destinations/${dest.id}`}>
              <Card className="overflow-hidden group hover:-translate-y-1 transition-transform cursor-pointer border-none shadow-sm hover:shadow-lg">
                <div className="relative h-64">
                  <Image
                    src={dest.img}
                    alt={dest.name}
                    fill
                    className="object-cover transition-transform group-hover:scale-105"
                    data-ai-hint={dest.hint}
                  />
                </div>
                <CardContent className="p-4 bg-white">
                  <h3 className="font-headline font-semibold text-lg">{dest.name}</h3>
                  <div className="flex items-center text-sm text-muted-foreground mt-1">
                    <MapPin className="w-3 h-3 mr-1" /> Explore hidden gems
                  </div>
                </CardContent>
              </Card>
            </Link>
          ))}
        </div>
      </section>

      {/* Call to Action for Guides */}
      <section className="container mx-auto px-4">
        <div className="bg-primary rounded-3xl p-8 md:p-16 text-center space-y-6 text-primary-foreground relative overflow-hidden">
          <div className="absolute top-0 right-0 p-4 opacity-10">
            <Users className="w-64 h-64 rotate-12" />
          </div>
          <h2 className="font-headline text-3xl md:text-5xl font-bold max-w-2xl mx-auto">Are you a Local Expert?</h2>
          <p className="text-lg opacity-90 max-w-xl mx-auto">
            Join our global community of guides and share your passion for your city with travelers from around the world.
          </p>
          <div className="pt-4">
            <Link href="/guides/register">
              <Button size="lg" className="bg-accent text-white hover:bg-accent/90 rounded-full h-12 px-8">
                Register as a Guide Today
              </Button>
            </Link>
          </div>
        </div>
      </section>
    </div>
  );
}
